### ISSUE TITLE
My dimensions box still can not show up in my abstract pages

### ISSUE THREAD

**Issue by prazetyo** [eprintsug/dimensions-badge#5]
I already activate dimensions badges from eprints bazaar, but after I reload configuration and generate abstract and views, the dimension box still can not show up.

Is there any tips how to show this badge on my summary page???

Thank you

**Comment by jesusbagpuss** [comment]
Hi,
From the EP-Tech list, it sounds like you solved this issue.

I have updated the [README](https://github.com/eprintsug/dimensions-badge/blob/main/README.md) for the code to make it clearer that the item needs a relevant identifier, and to highlight the advice from Dimensions themselves.
